#!/bin/bash

show_progress()
{
printf "Preparing environment..."

while true; do
  grep -i "done" /root/init-env/init-env.status &> /dev/null
  if [[ "$?" -ne 0 ]]; then
    # env is not ready yet
    printf "."
    sleep 1
  else
    printf "\n"
    break
  fi
done
}

show_progress
