#!/bin/bash

# set prompt
export PS1="\n\[\e[1m\]\[\e[33m\w\]\[\e[33m\] $ \[\e[0m\]"

# enable bash completion
source /etc/bash_completion

# go to /workspace directory
cd /workspace

# export env vars
export JAVA_HOME=/usr/lib/jvm/default-java/jre
export GITHUB_NS=springone-tour-2020-cicd
