#!/bin/bash

mkdir -p /root/init-env
cd /root/init-env

# Redirect output to log file
exec &>>  init-env.log

printf "" > init-env.status
echo "$(date)"
########## NO CHANGES ABOVE THIS LINE ##########

#echo "### Create a workspace directory and cd into it"
#mkdir workspace
#cd workspace
#echo "### Create setting up workspace directory"

git clone https://github.com/springone-tour-2020-cicd/tekton-labs.git /root/tekton-labs
curl -LO https://github.com/tektoncd/cli/releases/download/v0.7.1/tkn_0.7.1_Linux_x86_64.tar.gz
sudo tar xvzf tkn_0.7.1_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn
minikube start

########## NO CHANGES BELOW THIS LINE ##########
# The following must be the last line
echo "done" >> init-env.status
