#!/bin/bash

mkdir -p /root/init-env
cd /root/init-env

# Redirect output to log file
exec &>> /root/init-env/init-env.log

printf "" > /root/init-env/init-env.status
echo "$(date)"
########## NO CHANGES ABOVE THIS LINE ##########

echo "### Creating workspace directory (cd into it in init-foreground, not here)"
mkdir /workspace
echo "### Finished creating workspace directory"

echo "### Configuring git global settings"
git config --global hub.protocol https
git config --global credential.helper cache
git config --global user.email "guest@example.com"
git config --global user.name "Guest User"
echo "### Finished configuring git global settings"

echo "### Installing hub CLI"
HUB_VERSION=2.14.2
curl -L https://github.com/github/hub/releases/download/v$HUB_VERSION/hub-linux-amd64-$HUB_VERSION.tgz | tar zx && \
     ./hub-linux-amd64-$HUB_VERSION/install && \
     rm -rf hub-linux-amd64-$HUB_VERSION
echo "### Finished installing hub CLI"

echo "### Cloning kustomize labs repo"
git clone https://github.com/springone-tour-2020-cicd/kustomize-labs.git /root/kustomize-labs
echo "### Finished cloning kustomize labs repo"

echo "### Installing Kustomize CLI"
curl -LO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
tar xvzf kustomize_v3.5.4_linux_amd64.tar.gz -C /usr/local/bin/ kustomize
echo "### Finished installing Kustomize CLI"

# Leave this as the last task in this script
echo "### Waiting for Kubernetes nodes 'ready' status"
until `which kubectl`; do sleep 1; done;
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
until kubectl get nodes -o jsonpath="$JSONPATH" | grep "Ready=True"; do sleep 1; done
echo "### Finished waiting for Kubernetes nodes 'ready' status"

########## NO CHANGES BELOW THIS LINE ##########
# The following must be the last line
echo "done" >> /root/init-env/init-env.status
