#!/bin/bash

mkdir -p /root/init-env
cd /root/init-env

# Redirect output to log file
exec &>>  init-env.log

printf "" > init-env.status
echo "$(date)"
########## NO CHANGES ABOVE THIS LINE ##########

#echo "### Create a workspace directory and cd into it"
#mkdir workspace
#cd workspace
#echo "### Create setting up workspace directory"

echo "### Configuring git global settings"
#git config --global hub.protocol https
git config --global credential.helper cache
git config --global user.email "guest@example.com"
git config --global user.name "Guest User"
echo "### Finished configuring git global settings"

########## NO CHANGES BELOW THIS LINE ##########
# The following must be the last line
echo "done" >> init-env.status
