#!/bin/bash

# export PS1="\n\[\033[0m\]\w\$ "

# config command line prompt to show git branch status
source /usr/lib/git-core/git-sh-prompt
export GIT_PS1_SHOWDIRTYSTATE=yes
export PS1="\n\[\e[35m\]\$(__git_ps1) \[\e[33m\]\w\[\e[0m\]\n\$ "

# enable bash completion
source /etc/bash_completion
