#!/bin/bash

mkdir -p /root/init-env
cd /root/init-env

# Redirect output to log file
exec &>> /root/init-env/init-env.log

printf "" > /root/init-env/init-env.status
echo "$(date)"
########## NO CHANGES ABOVE THIS LINE ##########

echo "### Creating workspace directory (cd into it in init-foreground, not here)"
mkdir /workspace
echo "### Finished creating workspace directory"

echo "### Configuring git global settings"
git config --global hub.protocol https
git config --global credential.helper cache
git config --global user.email "guest@example.com"
git config --global user.name "Guest User"
echo "### Finished configuring git global settings"

echo "### Installing Tekton CLI (tkn)"
git clone https://github.com/springone-tour-2020-cicd/tekton-labs.git /root/tekton-labs
curl -LO https://github.com/tektoncd/cli/releases/download/v0.10.0/tkn_0.10.0_Linux_x86_64.tar.gz
sudo tar xvzf tkn_0.10.0_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn
echo "### Finished installing Tekton CLI (tkn)"

echo "### Installing pack CLI"
curl -L https://github.com/buildpacks/pack/releases/download/v0.11.2/pack-v0.11.2-linux.tgz | tar zx && \
    chmod +x pack && \
    mv pack /usr/local/bin/pack
echo "### Finished installing pack CLI"

echo "### Installing kpack logs CLI"
curl -L https://github.com/pivotal/kpack/releases/download/v0.0.9/logs-v0.0.9-linux.tgz | tar zx && \
    chmod +x logs && \
    mv logs /usr/local/bin/logs
echo "### Finished installing kpack logs CLI"

echo "### Installing yq CLI"
wget -o- -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
chmod +x /usr/local/bin/yq
echo "### Finished installing yq CLI"

# Leave this as the last task in this script
echo "### Waiting for Kubernetes nodes 'ready' status"
until `which kubectl`; do sleep 1; done;
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
until kubectl get nodes -o jsonpath="$JSONPATH" | grep "Ready=True"; do sleep 1; done
echo "### Finished waiting for Kubernetes nodes 'ready' status"

########## NO CHANGES BELOW THIS LINE ##########
# The following must be the last line
echo "done" >> /root/init-env/init-env.status
